---
services:
  db:
    image: "docker.io/library/mariadb:11"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: localdev
    ports:
      - 33066:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - traefik # Connect db to the traefik network

  web:
    env_file:
      - .env
    build: .
    command: "rails server -b 0.0.0.0"
    #command: tail -f /dev/null
    # command: "bundle install && rails server -b 0.0.0.0"
    # command: "bundle clean --force && rails server -b 0.0.0.0"
    volumes:
      - .:/app
#      - /app/node_modules
    ports:
      - "3000:3000"
      # Ports required for debugging
      - "1234:1234"
      - "26166:26168"
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lobsters.rule=Host(`${WEB_HOST}`)"
      - "traefik.http.services.lobsters.loadbalancer.server.port=3000"

      # - "traefik.http.routers.lobsters.entrypoints=web"

      - "traefik.http.routers.lobsters.entrypoints=websecure"
      - "traefik.http.routers.lobsters.tls=true"
      - "traefik.http.routers.lobsters.tls.certresolver=myresolver"
      - "traefik.docker.network=traefik"
      ##
      - "traefik.http.services.lobsters.loadbalancer.sticky=true"
      - "traefik.http.services.lobsters.loadbalancer.sticky.cookie.name=sticky_cookie"
      - "traefik.http.services.lobsters.loadbalancer.sticky.cookie.secure=true"
    networks:
      - traefik

volumes:
  db_data: {}

networks:
  traefik:
    external: true

